rvm:
  - 1.9.3
  - 2.0.0

env:
  - CHEF_VERSION="master"
  - CHEF_VERSION="~> 12.0"
  - CHEF_VERSION="< 12"

matrix:
  exclude:
  - rvm: 1.9.3
    env: CHEF_VERSION="master"
  - rvm: 1.9.3
    env: CHEF_VERSION="~> 12.0"

script: bundle exec rake spec