sudo: false
language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.5.5
    - rvm: 2.6.3
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

bundler_args: --without docs development

script: bundle exec rake
